[theme]
base = "dark"
primaryColor = "#C99A45"
backgroundColor = "#090909"
secondaryBackgroundColor = "#151515"
textColor = "#F2F2F2"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false